[project]
name = "voice-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mistralai>=1.12.4",
    "openai>=2.24.0",
    "pyqt6==6.9.0",
    "python-dotenv>=1.2.1",
]
